[tool.poetry]
name = "cipher_hc3245"
version = "0.1.1"
description = ""
authors = ["Hongbin Chen <hc3245@columbia.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
